server:
  port: 9001

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.143.224.91:8761/eureka/
  instance:
    hostname: 3.143.224.91
